export const CAMPAIGNS_REQUEST = 'CAMPAIGNS_REQUEST'
export const CAMPAIGNS_RECEIVED = 'CAMPAIGNS_COMPLETED'
export const CAMPAIGNS_FALTURE = 'CAMPAIGNS_FALTURE'

export const CAMPAIGN_RECEIVED = 'CAMPAIGN_COMPLETED'
export const CREATE_CAMPAIGN_RECEIVED = 'CREATE_CAMPAIGN_COMPLETED'

export const CHECK_CAMPAIGN_RECEIVED = 'CHECK_CAMPAIGN_RECEIVED'